### ISSUE TITLE
Typo in the bibtex of the project page

### ISSUE THREAD

**Issue by bluestyle97** [NasirKhalid24/CLIP-Mesh#10]
Hi, I notice that there is a typo in the bibtex of the [project page](https://www.nasir.lol/clipmesh): `journal` is misspelled as `joural`. This will cause a citation problem when others want to cite CLIP-Mesh in their papers and copy the bibtex from the project page. I encountered this problem in a previous paper submission :(. I hope you can fix it soon.

**Comment by NasirKhalid24** [comment]
Fixed - thanks!
