### ISSUE TITLE
How do I visualize the generated mesh on a website?

### ISSUE THREAD

**Issue by zhizdev** [NasirKhalid24/CLIP-Mesh#3]
Hi Nasir, 

Thanks for the great work! This is super creative and the results look better than DreamFields. 

Quick question: how do I visualize the generate meshes on a website, like the meshes on your project website (https://github.com/NasirKhalid24/CLIP-Mesh)? 

I tried to convert the .obj to .gltf but without any success. The converted texture looks very different on https://modelviewer.dev/. 

Thanks!

**Comment by NasirKhalid24** [comment]
For the website it uses [model-viewer](https://github.com/google/model-viewer) and loads a .glb file

The models were actually loaded in to blender and then exported - I suspect the alpha channel of the texture maps are not being applied as thats the common error when the textures look very different
