### ISSUE TITLE
how to visualize multiple generated obj objects Simultaneously

### ISSUE THREAD

**Issue by runzeer** [NasirKhalid24/CLIP-Mesh#6]
Dear Prof；
    Thanks for your excellent paper. I just wanted to know how to visualize the multiple generated objects simultaneously just like your paper Figure 1

**Comment by runzeer** [comment]
Or can you provide the colab script for your scene generation in paper figure 1?

**Comment by NasirKhalid24** [comment]
For Figure1 all the shapes are individually generated and then loaded and placed in a Blender scene manually by me - they are not simultaneously generated
