### ISSUE TITLE
Different mesh error

### ISSUE THREAD

**Issue by saatvikmah** [NasirKhalid24/CLIP-Mesh#9]
Getting errors when introduncing a new mesh for texture generation. The in-house meshes like spot.obj etc are working fine, but meshes generated from OpenAI's Point-E are not working well.

**Comment by NasirKhalid24** [comment]
Could you try out the points here:

https://github.com/NasirKhalid24/CLIP-Mesh/blob/master/assets/FAQ.md#i-added-a-custom-mesh-to-generate-with-and-the-program-just-crashes
